language: cpp

#compiler:
#  - gcc
#  - clang TODO!

sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      env: PYTHONVER=3.5
    - os: linux
      dist: trusty
      env: PYTHONVER=2.7
    - os: osx
      osx_image: xcode8.2
      env: PYTHONVER=2.7
  exclude:
    - os: osx
      osx_image: xcode8.2
      env: PYTHONVER=3.5

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g"); fi
  - if [ $TRAVIS_OS_NAME == osx ]; then export PATH=/usr/bin:$PATH; fi

  #- if [ $TRAVIS_OS_NAME == linux ]; then sudo sh -c 'echo "deb https://cloud.r-project.org/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'; fi
  #- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ zesty main universe"; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi

install:
  ### LINUX
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install --no-install-recommends -t zesty -y lcov libnlopt-dev libgsl0-dev libeigen3-dev libboost1.63-dev libboost-python1.63-dev python$PYTHONVER-dev python$([ "${PYTHONVER:0:1}" == 3 ] && echo ${PYTHONVER:0:1} || echo "")-numpy; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install --no-install-recommends -t zesty -y r-base-dev g++; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install --no-install-recommends -t zesty -y doxygen doxygen-doc doxygen-gui graphviz; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get autoremove; fi # in particular remove old compilers so that new ones are the default
  - if [ $TRAVIS_OS_NAME == linux ]; then export CMAKE_ARGS="$CMAKE_ARGS -DPYTHON_EXECUTABLE=/usr/bin/python$PYTHONVER -DPYTHON_INCLUDE_DIR=/usr/include/python$PYTHONVER"; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then export R_PACKAGES='c("VineCopula")'; fi

  ### OSX
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew tap homebrew/science && brew install lcov eigen gsl nlopt boost-python numpy; fi

  - if [ $TRAVIS_OS_NAME == osx ]; then rm /usr/local/include/c++; fi # https://github.com/Homebrew/brew/issues/1742#issuecomment-277308817
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install r; fi

  - if [ $TRAVIS_OS_NAME == osx ]; then brew install doxygen graphviz; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then export R_PACKAGES='c("VineCopula")'; fi

  ### Common
  - sudo Rscript -e 'withCallingHandlers(install.packages('$R_PACKAGES', repos="http://cran.rstudio.com/"), warning=function(x) { message(x); quit(status=1, save="no") })'

script:
  - echo $CMAKE_ARGS
  - mkdir bin
  - mkdir release
  - mkdir debug
  - cd debug
  - cmake .. $CMAKE_ARGS -DOPT_ASAN=OFF -DCMAKE_BUILD_TYPE=Debug && make vinecopulib_coverage
  - make test || cat Testing/Temporary/LastTest.log / # "/" intentional! (just to make cat exit with an error code)
  - cd ../release
  - cmake .. $CMAKE_ARGS -DCMAKE_BUILD_TYPE=Release && make && make doc
  - make test || cat Testing/Temporary/LastTest.log / # "/" intentional! (just to make cat exit with an error code)
  - cd ../bin
  - ./test_all

after_success:
    # Creating report
  - cd debug
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out external includes
  - lcov --remove coverage.info '/Applications/*' --output-file coverage.info # filter out more external includes
  - lcov --remove coverage.info '*test*' --output-file coverage.info # filter out test
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

notifications:
  email:
    - thibault.vatter@gmail.com
