language: cpp
matrix:
  include:
#    - os: linux
#      dist: trusty
#      sudo: required
    - os: osx
      sudo: required

osx_image: xcode8.2

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo sh -c 'echo "deb https://cloud.r-project.org/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi

install:
  ### LINUX
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install libeigen3-dev libnlopt-dev libgsl0-dev libboost-all-dev; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install r-base; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install doxygen doxygen-doc doxygen-gui graphviz; fi

  ### OSX
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew tap homebrew/science && brew install eigen gsl nlopt; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then brew install boost --with-python; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install boost-python; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew tap homebrew/science && brew install eigen gsl nlopt r; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then brew install cask && brew install r; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install doxygen; fi

  ### Common
  - sudo Rscript -e 'install.packages(c("Rcpp","RInside","RcppEigen","VineCopula"), lib="/usr/lib/R/library", repos="http://cran.rstudio.com/")'

script:
  - mkdir bin
  - mkdir release
  - mkdir debug
  - cd debug
  - cmake .. -DCMAKE_BUILD_TYPE=Debug && make && make doc
  - cd ../bin
  - ./test_bicop_parametric
  - ./test_bicop_class
  - ./test_bicop_select
  - ./test_bicop_trafokernel
  - cd ../release
  - cmake .. -DCMAKE_BUILD_TYPE=Release && make && make doc
  - cd ../bin
  - ./test_bicop_parametric
  - ./test_bicop_class
  - ./test_bicop_select
  - ./test_bicop_trafokernel

notifications:
  email:
    - thibault.vatter@gmail.com
